### PR TITLE
TS migration ,  new questions

### PR DESCRIPTION
**Pull request by anikethsaha**
Can't seperate the PRs man , the whole code is bundled up together.

### CODE REVIEW

**Comment by rishabh3112** [comment]
Thanks for the PR again and the amount of work you have put into it.

Sorry, but I don't like the output formatting and updated project structure introduced here.
That's why separate PRs for each concern, would be easy for me to look into each change and guide accordingly as per requirement.

Hope you get my point :)

**Comment by anikethsaha** [comment]
Can you elaborate on what you don't like about the output format and the project structure?

**Comment by rishabh3112** [comment]
Ya sure,

First the output format . Output isn't clean and offers friction to UX. I am pretty happy how output shown to user currently. So keep it the way it is now.

And as far as project structure is concerned, the directory structure should be like we have `src` directory with all the TS code and output compiled files to a `lib` folder.

Also don't offer any functionality all ready implemented as it might not be of use to the user writing the scaffolds. Like split chunks are added here.

You can start with TS migration IMO.

**Comment by anikethsaha** [comment]
As far as the output is concerned, I don't think it is bringing any friction, I guess its more declarative.
Yeah your project structure point I agree, it can be more organized.
It's in optional, the slipt chunk one so I guess it can be a more user-friendly approach.

All these changes which I added are what I think a scaffold starter/generator should have and it's fine also if you can code it with yourself as your approach. So I am closing this PR, I hope to see this feature soon. 
:)

Typescript is not mandatory but it's always good to have so it's on you 👍

**Pull request closed without merging**
